server:
  port: 11000

spring:
  application:
    name: provider-server


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      #需要注册给Eureka Server的地址，也就是将自己注册给哪一个Eureka Server
      defaultZone: http://localhost:13000/eureka,http://localhost:13002/eureka